apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: context
on:
  workflow_dispatch:

env:
  ISPREPROD: ${{ contains(cloudbees.api.url,'preprod') && 'It is preprod' || 'It is probably prod' }}
  ISPREPRODTF: ${{ contains(cloudbees.api.url,'preprod') && true || false }}

jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo cloudbees.api.url: ${{ cloudbees.api.url }}
          echo cloudbees.api.token: ${{ cloudbees.api.token }}
          echo cloudbees.home: ${{ cloudbees.home }}
          echo cloudbees.run_id: ${{ cloudbees.run_id }}
          echo cloudbees.run_attempt: ${{ cloudbees.run_attempt }}
          echo step.id: ${{ step.id }}
          echo Is it preprod: $ISPREPROD
          echo Is it preprod TF: $ISPREPRODTF