apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Test saving to my repo
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - uses: cloudbees-demos/comp1/install@main
        name: Install comp1
        kind: deploy
        with:
          version: 1
